### PR TITLE
Bugfix. …

### PR DESCRIPTION
**Pull request by demolitionb**
rebin_piecewise_constant(x1, y1, x2): has to return y2 instead of y in the case # the first bin totally covers x1 range

### CODE REVIEW

**Comment by demolitionb** [comment]
matplotlib should be imported too...

**Comment by andyfaff** [comment]
Wasn't clear why you closed the PR.

**Comment by demolitionb** [comment]
The problem was, that your function crashes when X1 and Y1 arrays are ordered reversely. It works fine when X1 goes from low to high like it should be.

**Comment by demolitionb** [comment]
But maybe it should return y2 anyway...

**Comment by andyfaff** [comment]
The use of searchsorted requires that x1 be sorted in ascending order. Not sure if searchsorted raises an Exception if it's not.

**Comment by demolitionb** [comment]
Got it. I looked through the code and now it's clear, that in the current form it only works for strictly ascending x1 arrays (non-overlapping)...

**Comment by jhykes** [comment]
@demolitionb Your changes look good to me. 

Do you also want to add a clarification in the function documentation that `x1` needs to be in ascending order? That might help prevent confusion for someone else.

**Comment by demolitionb** [comment]
I thought of that and also adding some np.nan_to_num() 's that I have to include. I encountered some more strange artifacts and would like to understand their origin and perhaps suggest a solution later...

**Pull request merged**
